version: '3.7'

services:
  postgres:
    image: 'bitnami/postgresql:latest'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=senha
      - POSTGRES_DB=nubank
    volumes:
      - polis_pg_data:/bitnami/postgresql

volumes:
  polis_pg_data:
